// public/registry/generated/react/react/badge.tsx
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  type ComponentPropsWithoutRef,
  type ReactNode,
} from "react";
import { badge } from "../components/badge";
import "../styles/badge.css";

export interface BadgeProps extends Omit<ComponentPropsWithoutRef<"span">, "variant" | "size"> {
  variant?: "default" | "secondary" | "outline" | "danger" | "success" | "warning";
  size?: "sm" | "md" | "lg";
  children?: ReactNode;
}

export const Badge = forwardRef<HTMLElement, BadgeProps>(
  function Badge(
    {
      variant = "default",
      size = "sm",
      children,
      ...props
    },
    forwardedRef,
  ) {
    const localRef = useRef<HTMLElement | null>(null);
    const instanceRef = useRef<ReturnType<typeof badge.mount> | null>(null);

    useImperativeHandle(
      forwardedRef,
      () => localRef.current as HTMLElement,
      [],
    );

    useEffect(() => {
      const element = localRef.current;
      if (!element) return;

      const instance = badge.mount(element, {
        variant,
        size,
      });
      instanceRef.current = instance;

      return () => {
        instance.destroy();
        instanceRef.current = null;
      };
    }, []);

    useEffect(() => {
      instanceRef.current?.update({
        variant,
        size,
      });
    }, [variant, size]);

    return (
      <span
        {...props}
        ref={localRef as never}
        data-bambi-badge=""
        data-variant={variant}
        data-size={size}
      >
        {children}
      </span>
    );
  },
);

// public/registry/generated/solid/solid/badge.tsx
import { createEffect, onCleanup, onMount, splitProps, type JSX } from "solid-js";
import { badge } from "../components/badge";
import "../styles/badge.css";

export interface BadgeProps
  extends JSX.HTMLAttributes<HTMLElement> {
  variant?: "default" | "secondary" | "outline" | "danger" | "success" | "warning";
  size?: "sm" | "md" | "lg";
}

export function Badge(props: BadgeProps) {
  const [local, rest] = splitProps(props, [
    "variant",
    "size"
  ]);
  let element!: HTMLElement;
  let instance: ReturnType<typeof badge.mount> | undefined;
  const variant = () => local.variant ?? "default";
  const size = () => local.size ?? "sm";

  onMount(() => {
    instance = badge.mount(element, {
        variant: variant(),
        size: size(),
    });
  });

  createEffect(() => {
    instance?.update({
        variant: variant(),
        size: size(),
    });
  });

  onCleanup(() => {
    instance?.destroy();
  });

  return (
    <span
      {...rest}
      ref={element}
      data-bambi-badge=""
      data-variant={variant()}
      data-size={size()}
    />
  );
}
