// public/registry/generated/react/react/tabs.tsx
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  type HTMLAttributes,
  type ReactNode,
} from "react";
import { tabs } from "../components/tabs";
import "../styles/tabs.css";

export interface TabsProps extends HTMLAttributes<HTMLElement> {
  value?: string;
  defaultValue?: string;
  orientation?: "horizontal" | "vertical";
  activationMode?: "automatic" | "manual";
  children?: ReactNode;
}

export const Tabs = forwardRef<HTMLElement, TabsProps>(
  function Tabs(
    {
      value,
      defaultValue,
      orientation = "horizontal",
      activationMode = "automatic",
      children,
      ...props
    },
    forwardedRef,
  ) {
    const localRef = useRef<HTMLElement | null>(null);
    const instanceRef = useRef<ReturnType<typeof tabs.mount> | null>(null);

    useImperativeHandle(
      forwardedRef,
      () => localRef.current as HTMLElement,
      [],
    );

    useEffect(() => {
      const element = localRef.current;
      if (!element) return;

      const instance = tabs.mount(element, {
        value,
        defaultValue,
        orientation,
        activationMode,
      });
      instanceRef.current = instance;

      return () => {
        instance.destroy();
        instanceRef.current = null;
      };
    }, []);

    useEffect(() => {
      instanceRef.current?.update({
        value,
        defaultValue,
        orientation,
        activationMode,
      });
    }, [value, defaultValue, orientation, activationMode]);

    return (
      <div
        {...props}
        ref={localRef as never}
        data-bambi-tabs=""
        data-value={value}
        data-default-value={defaultValue}
        data-orientation={orientation}
        data-activation-mode={activationMode}
      >
        {children}
      </div>
    );
  },
);

export interface TabsListProps extends HTMLAttributes<HTMLElement> {}

export const TabsList = forwardRef<HTMLElement, TabsListProps>(
  function TabsList(props, forwardedRef) {
    return (
      <div
        {...props}
        ref={forwardedRef as never}
        data-bambi-tabs-list=""
        role="tablist"
      />
    );
  },
);


export interface TabsTriggerProps extends HTMLAttributes<HTMLElement> {}

export const TabsTrigger = forwardRef<HTMLElement, TabsTriggerProps>(
  function TabsTrigger(props, forwardedRef) {
    return (
      <button
        {...props}
        ref={forwardedRef as never}
        data-bambi-tabs-trigger=""
        role="tab"
      />
    );
  },
);


export interface TabsContentProps extends HTMLAttributes<HTMLElement> {}

export const TabsContent = forwardRef<HTMLElement, TabsContentProps>(
  function TabsContent(props, forwardedRef) {
    return (
      <div
        {...props}
        ref={forwardedRef as never}
        data-bambi-tabs-content=""
        role="tabpanel"
      />
    );
  },
);

// public/registry/generated/solid/solid/tabs.tsx
import { createEffect, onCleanup, onMount, splitProps, type JSX } from "solid-js";
import { tabs } from "../components/tabs";
import "../styles/tabs.css";

export interface TabsProps
  extends JSX.HTMLAttributes<HTMLElement> {
  value?: string;
  defaultValue?: string;
  orientation?: "horizontal" | "vertical";
  activationMode?: "automatic" | "manual";
}

export function Tabs(props: TabsProps) {
  const [local, rest] = splitProps(props, [
    "value",
    "defaultValue",
    "orientation",
    "activationMode"
  ]);
  let element!: HTMLElement;
  let instance: ReturnType<typeof tabs.mount> | undefined;
  const value = () => local.value ?? undefined;
  const defaultValue = () => local.defaultValue ?? undefined;
  const orientation = () => local.orientation ?? "horizontal";
  const activationMode = () => local.activationMode ?? "automatic";

  onMount(() => {
    instance = tabs.mount(element, {
        value: value(),
        defaultValue: defaultValue(),
        orientation: orientation(),
        activationMode: activationMode(),
    });
  });

  createEffect(() => {
    instance?.update({
        value: value(),
        defaultValue: defaultValue(),
        orientation: orientation(),
        activationMode: activationMode(),
    });
  });

  onCleanup(() => {
    instance?.destroy();
  });

  return (
    <div
      {...rest}
      ref={element}
      data-bambi-tabs=""
      data-value={value()}
      data-default-value={defaultValue()}
      data-orientation={orientation()}
      data-activation-mode={activationMode()}
    />
  );
}
