// public/registry/generated/solid/solid/badge.tsx
import { createEffect, onCleanup, onMount, splitProps, type JSX } from "solid-js";
import { badge } from "../components/badge";
import "../styles/badge.css";

export interface BadgeProps
  extends JSX.HTMLAttributes<HTMLElement> {
  variant?: "default" | "secondary" | "outline" | "danger" | "success" | "warning";
  size?: "sm" | "md" | "lg";
}

export function Badge(props: BadgeProps) {
  const [local, rest] = splitProps(props, [
    "variant",
    "size"
  ]);
  let element!: HTMLElement;
  let instance: ReturnType<typeof badge.mount> | undefined;
  const variant = () => local.variant ?? "default";
  const size = () => local.size ?? "sm";

  onMount(() => {
    instance = badge.mount(element, {
        variant: variant(),
        size: size(),
    });
  });

  createEffect(() => {
    instance?.update({
        variant: variant(),
        size: size(),
    });
  });

  onCleanup(() => {
    instance?.destroy();
  });

  return (
    <span
      {...rest}
      ref={element}
      data-bambi-badge=""
      data-variant={variant()}
      data-size={size()}
    />
  );
}

// public/registry/generated/svelte/svelte/Badge.svelte
<script lang="ts">
  import { onDestroy, onMount } from "svelte";
  import { badge } from "../components/badge";
  import "../styles/badge.css";

  interface Props {
  variant?: "default" | "secondary" | "outline" | "danger" | "success" | "warning";
  size?: "sm" | "md" | "lg";
  children?: import("svelte").Snippet;
  [key: string]: unknown;
}

  let {
    variant = "default",
      size = "sm",
    children,
    ...rest
  }: Props = $props();

  let element: HTMLElement;
  let instance: ReturnType<typeof badge.mount> | undefined;

  $effect(() => {
    instance?.update({
    variant,
    size,
    });
  });

  onMount(() => {
    instance = badge.mount(element, {
    variant,
    size,
    });
  });

  onDestroy(() => {
    instance?.destroy();
  });
</script>

<span
  {...rest}
  bind:this={element}
  data-bambi-badge=""
  data-variant={variant}
  data-size={size}
>
  {@render children?.()}
</span>
