// public/registry/generated/solid/solid/button.tsx
import { createEffect, onCleanup, onMount, splitProps, type JSX } from "solid-js";
import { button } from "../components/button";
import "../styles/button.css";

export interface ButtonProps
  extends JSX.HTMLAttributes<HTMLElement> {
  variant?: "primary" | "secondary" | "outline" | "ghost" | "danger" | "success" | "warning";
  size?: "sm" | "md" | "lg" | "icon";
  disabled?: boolean;
  loading?: boolean;
}

export function Button(props: ButtonProps) {
  const [local, rest] = splitProps(props, [
    "variant",
    "size",
    "disabled",
    "loading"
  ]);
  let element!: HTMLElement;
  let instance: ReturnType<typeof button.mount> | undefined;
  const variant = () => local.variant ?? "primary";
  const size = () => local.size ?? "md";
  const disabled = () => local.disabled ?? undefined;
  const loading = () => local.loading ?? undefined;

  onMount(() => {
    instance = button.mount(element, {
        variant: variant(),
        size: size(),
        disabled: disabled(),
        loading: loading(),
    });
  });

  createEffect(() => {
    instance?.update({
        variant: variant(),
        size: size(),
        disabled: disabled(),
        loading: loading(),
    });
  });

  onCleanup(() => {
    instance?.destroy();
  });

  return (
    <button
      {...rest}
      ref={element}
      data-bambi-button=""
      data-variant={variant()}
      data-size={size()}
      data-disabled={disabled() ? "true" : undefined}
      data-loading={loading() ? "true" : undefined}
    />
  );
}

// public/registry/generated/react/react/button.tsx
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  type HTMLAttributes,
  type ReactNode,
} from "react";
import { button } from "../components/button";
import "../styles/button.css";

export interface ButtonProps extends HTMLAttributes<HTMLElement> {
  variant?: "primary" | "secondary" | "outline" | "ghost" | "danger" | "success" | "warning";
  size?: "sm" | "md" | "lg" | "icon";
  disabled?: boolean;
  loading?: boolean;
  children?: ReactNode;
}

export const Button = forwardRef<HTMLElement, ButtonProps>(
  function Button(
    {
      variant = "primary",
      size = "md",
      disabled,
      loading,
      children,
      ...props
    },
    forwardedRef,
  ) {
    const localRef = useRef<HTMLElement | null>(null);
    const instanceRef = useRef<ReturnType<typeof button.mount> | null>(null);

    useImperativeHandle(
      forwardedRef,
      () => localRef.current as HTMLElement,
      [],
    );

    useEffect(() => {
      const element = localRef.current;
      if (!element) return;

      const instance = button.mount(element, {
        variant,
        size,
        disabled,
        loading,
      });
      instanceRef.current = instance;

      return () => {
        instance.destroy();
        instanceRef.current = null;
      };
    }, []);

    useEffect(() => {
      instanceRef.current?.update({
        variant,
        size,
        disabled,
        loading,
      });
    }, [variant, size, disabled, loading]);

    return (
      <button
        {...props}
        ref={localRef as never}
        data-bambi-button=""
        data-variant={variant}
        data-size={size}
        data-disabled={disabled ? "true" : undefined}
        data-loading={loading ? "true" : undefined}
      >
        {children}
      </button>
    );
  },
);
